Adding Installation Guide to the Reference documentation
secure-device-onboard/docs pull request #13
Opened 2020-08-27 08:56 UTC by DukeDavis12

Adding the Installation Guide to the reference documentation.
     Includes documentation for the installation of specific docker-engine
     and docker-compose which SDO uses.

Signed-off-by: Davis Benny <davis.benny@intel.com>

2020-08-28 10:23 UTC, prateekcr commented on docs/installation.md
> +[4.  Other Development Tools](#other-development-tools)
Extra space.

2020-08-28 10:24 UTC, prateekcr commented on docs/installation.md
> + sudo add-apt-repository \ "deb [arch=amd64] https://download.docker.com/linux/ubuntu \ $(lsb_release -cs) \ stable"
Extra space

2020-09-02 10:42 UTC, KiranSukhavasi requested changes

2020-09-02 10:42 UTC, KiranSukhavasi commented on docs/installation.md
> +4. Next, create a directory named **_.docker_** in the user home path    (**~/**) and a create a file named **_config.json_** if not present,  add the following content.
extra spaces are found in few places

2020-09-02 10:42 UTC, KiranSukhavasi commented on docs/installation.md
> +6. To ensure that  the proxies are set  successfully, run the following command
extra spaces are found

2020-09-02 10:42 UTC, KiranSukhavasi commented on docs/installation.md
> +3 . To set the correct system time
Can we explain why this is required to set? might be the effect if not set proper time?

2020-09-02 10:53 UTC, KiranSukhavasi requested changes
Please take care of the extra spaces. I found quite a few.

2020-09-02 10:53 UTC, KiranSukhavasi commented on docs/installation.md
> +This document can be used as a quick start guide to setup the Dev environment. Please review the system requirements listed below before moving forward with the SDO installation and deployment.
Is this "Dev Environment" or "Docker environment" ?

2020-09-02 10:53 UTC, KiranSukhavasi commented on docs/installation.md
> +1 . Removing the older versions of Docker. If these are installed, uninstall them:
This means that any newer version of Docker should be ok is it?

2020-09-02 12:20 UTC, KiranSukhavasi approved these changes, later dismissed

2020-09-03 03:43 UTC, TomBarnes commented on docs/installation.md
> +
To install the specific version of docker-compose (here 1.21.2) follow the given steps below
consider instead
To install a specific version of docker-compose (for example 1.21.2) follow these steps:

2020-09-03 03:44 UTC, TomBarnes submitted a review, later dismissed
I reviewed and approve this PR

I made a suggestion on line 94 that improves readability marginally but is not essential.

2020-09-04 07:00 UTC, prateekcr approved these changes

2020-09-04 07:03 UTC, KiranSukhavasi approved these changes

2020-09-04 07:06 UTC, trbehera approved these changes

2020-09-04 07:11 UTC, merged

2020-09-04 07:11 UTC, Darshini-Parikh93 commented on docs/installation.md
> +[https://docs.docker.com/engine/install/ubuntu/#installation-methods](https://docs.docker.com/engine/install/ubuntu/#installation-methods)
Links are not rendering on new line. Put <br> at the end of each reference to ensure that

2020-09-04 07:13 UTC, Darshini-Parikh93 commented on docs/installation.md
> +## Table of Contents
Table of contents, not rendering on new line each. Put "\<br>" at the end of each item to ensure that.

2020-09-04 07:16 UTC, Darshini-Parikh93 commented on docs/installation.md
> +1 . Removing the older versions of Docker. If these are installed, uninstall them:
Would suggest to use bulleted list instead of manual numbering.

2020-09-04 07:21 UTC, Darshini-Parikh93 commented on docs/installation.md
> +sudo apt-get update
Put a "$" sign before the command, to indicate commandline

2020-09-04 07:22 UTC, Darshini-Parikh93 commented on docs/installation.md
> +	 sudo docker run hello-world
Enclose this in command notation

2020-09-04 07:24 UTC, Darshini-Parikh93 commented on docs/installation.md
> +	`sudo systemctl show --property Environment docker`
This is a command, notation in which its enclosed is incorrect.

2020-09-04 07:27 UTC, Darshini-Parikh93 commented on docs/installation.md
> +  `sudo apt install openjdk-11-jdk-headless`
This is a command, notation in which its enclosed is incorrect.

2020-09-04 07:27 UTC, Darshini-Parikh93 commented on docs/installation.md
> +  `sudo apt install maven`
This is a command, notation in which its enclosed is incorrect.

2020-09-04 07:28 UTC, Darshini-Parikh93 commented on docs/installation.md
> +    `mkdir -p /etc/systemd/system/docker.service.d`
This is a command, notation in which its enclosed is incorrect.