Fixing typo errors in docs/home README file
secure-device-onboard/docs pull request #25
Opened 2020-09-01 09:48 UTC by DukeDavis12

Fixing typo errors in docs/home  README file. Includes
   spelling errors as well as grammatical errors.

Signed-off-by: Davis Benny <davis.benny@intel.com>

2020-09-01 09:49 UTC, DukeDavis12 commented on docs/index.md
> -**Client SDK** - The Client SDK provides devices with an implementation of the DI protocol, which initializes the device with credentials, the TO1 protocol, which connects the device to a Rendezvous
Linus --> spelling error.

2020-09-01 09:55 UTC, DukeDavis12 commented on docs/index.md
> -During deployment of a device enable with the Secure Device Onboard solution, all the installer needs to do is add power to the device and connect it to the Internet. The device automatically and rap
During deployment of a device enable with the Secure Device Onboard solution -->  During deployment of a device enabled with the Secure Device Onboard solution.

2020-09-01 09:55 UTC, DukeDavis12 commented on docs/index.md
> -**Client SDK** - The Client SDK provides devices with an implementation of the DI protocol, which initializes the device with credentials, the TO1 protocol, which connects the device to a Rendezvous
Linus --> spelling

2020-09-01 09:55 UTC, DukeDavis12 commented on docs/index.md
> -**Rendezvous Service** - The Rendezvous Service software provides a complete Rendezvous service, and implements the TO0 and TO1 protocols required for device registration and discovery.  It can be ru
It appears that we have an unnecessary comma in a compound predicate.

2020-09-01 09:55 UTC, DukeDavis12 commented on docs/index.md
> -**IOT Platform SDK** - The IOT Platform SDK provides micro-services to facilitate integration of an IOT Platform in the Secure Device Onboard processes. It implements the TOO protocol required for de
the noun phrase "Integration" seems to be missing a determiner before it. So adding an article.

2020-09-01 09:55 UTC, DukeDavis12 commented on docs/index.md
> -This section describes a typical process in which Secure Device Onboard is used to automatically and securely onboard a device onto an owners network.  Those process include:
It appears that the plural demonstrative  "those"  is modifying the singular noun.  So changing process to processes.

2020-09-01 09:55 UTC, DukeDavis12 commented on docs/index.md
> -The following diagram shows an example of a possible IoT supply chain and the steps taken by each participant in the Secure Device Onboard service. Each step is described in more detail in following
missing article.

2020-09-01 09:55 UTC, DukeDavis12 commented on docs/index.md
> -To facilitate easy integration with Secure Device Onboard, the IOT Platform can use the Secure Device Onboard *IOT Platform SDK*, which implements the protocol features required by the IPT Platform t
IPT -> spelling error.

2020-09-01 09:55 UTC, DukeDavis12 commented on docs/index.md
> -### Distributers and Resellers
Wrong Usage -> Distributers

2020-09-01 17:53 UTC, trbehera requested changes

2020-09-01 17:53 UTC, trbehera commented on docs/community.md
> +Report issues using each component's respective Github repository.
GitHub => GitHub

That is a more standard way to refer.

2020-09-01 17:53 UTC, trbehera commented on docs/community.md
> +Report issues using each component's respective Github repository.
Github => GitHub

2020-09-02 09:51 UTC, trbehera approved these changes, later dismissed

2020-09-02 09:58 UTC, KiranSukhavasi approved these changes, later dismissed

2020-09-02 10:06 UTC, v-Vasavi reviewed
1. all the installer needs to do is "to"  add power would be good to add a "to" there
2. Line 61 - Should it be "These processes" instead of Those

2020-09-02 10:10 UTC, trbehera commented
> all the installer needs to do is "to"  add power would be good to add a "to" there

Updated.

> Line 61 - Should it be "These processes" instead of Those

Line 61=> It feels okay to use 'Those' here.

2020-09-02 10:15 UTC, trbehera approved these changes

2020-09-02 10:16 UTC, KiranSukhavasi approved these changes

2020-09-02 10:42 UTC, merged