fix: correcting for 1.9 release
secure-device-onboard/docs pull request #39
Opened 2020-09-01 13:37 UTC by nbmaiti

Signed-off-by: Nabendu Maiti <nabendu.bikash.maiti@intel.com>

2020-09-02 11:19 UTC, trbehera requested changes

2020-09-02 11:19 UTC, trbehera commented on docs/client-sdk/client-sdk-reference-guide.md
> +|    Software                                      |    ·      Linux\* Ubuntu\* 18.04 using   OpenSSL\* 1.1.1g <br/>·      JDK11  <br/> ·      SDO release binaries package (for running test servers)
Reference to Ubuntu 16.04 should be removed.

Additional Ubuntu\* 16.04/18.04 ==> Additional Ubuntu\* 18.04

2020-09-02 11:25 UTC, trbehera approved these changes

2020-09-03 03:51 UTC, KiranSukhavasi approved these changes

2020-09-03 03:52 UTC, merged