Updating the Iot-Platform-SDK documents.
secure-device-onboard/docs pull request #6
Opened 2020-07-27 10:49 UTC by prateekcr

Updating the Iot-Platform-SDK documents as per the recent changes.

Signed-off-by: Chandrakar, Prateek <prateek.chandrakar@intel.com>

2020-07-27 16:00 UTC, johneasterday submitted a review, later dismissed

2020-09-02 08:11 UTC, KiranSukhavasi commented on docs/iot-platform-sdk/introduction.md
> +This component is responsible for the scheduling and completion of TO0 for multiple ownership vouchers. It makes use of  the CRIs libto0client to perform TO0 for any device. This component is compris
Plz change CRIs -> PRIs

2020-09-02 08:32 UTC, trbehera requested changes

2020-09-02 08:32 UTC, trbehera commented on docs/iot-platform-sdk/running-the-demo.md
> +    When running the demo in a single machine, the ownership voucher must be created such that the IP address of the Rendezvous service is present, instead of 'localhost' in the Rendezvous informatio
in a single machine => in multiple machines,

2020-09-02 08:32 UTC, trbehera commented on docs/iot-platform-sdk/running-the-demo.md
> +Each docker service of Iot-Platform-SDK has its own configuration file with extension '.env'. When each service starts, the properties stored in the '.env' files will be set as environment variables
Iot-Platform-SDK => IOT Platform SDK

2020-09-02 08:32 UTC, trbehera commented on docs/iot-platform-sdk/running-the-demo.md
> +Each docker service of Iot-Platform-SDK has its own configuration file with extension '.env'. When each service starts, the properties stored in the '.env' files will be set as environment variables
explicitely => explicitly

2020-09-02 08:32 UTC, trbehera commented on docs/iot-platform-sdk/running-the-demo.md
> +    In rest of the guide, the original name of the properties specified in the runnable scripts: run-ocs, run-ops and run-to0scheduler, will be referenced, instead of the names present in the .env fi
explicitely => explicitly

2020-09-02 08:32 UTC, trbehera commented on docs/iot-platform-sdk/running-the-demo.md
> +    By default, To0Scheduler is configured to verify Rendezvous's incoming server certificate during TLS handshake for all outgoing HTTPS requests to Rendezvous, made during TO0. To disable this cert
**Rendezvous service's** incoming server 
HTTPS requests to the **Rendezvous service**.
Can be removed **, made during TO0**

2020-09-02 10:23 UTC, KiranSukhavasi approved these changes, later dismissed

2020-09-02 11:09 UTC, trbehera commented on docs/iot-platform-sdk/introduction.md
> +**to0serviceimpl**: This module contains the spring boot application and its configuration classes. It imports the 'libto0' component as a dependency, configures it, and provides implementations of i
receiveing => receiving

2020-09-02 11:09 UTC, trbehera commented on docs/iot-platform-sdk/running-the-demo.md
> +    When running the demo in a multiple machines, the ownership voucher must be created such that the IP address of the Rendezvous service is present, instead of 'localhost' in the Rendezvous informa
in a multiple machines => in multiple machines

2020-09-02 11:40 UTC, prateekcr commented
Updated as per comments.

2020-09-02 12:47 UTC, KiranSukhavasi approved these changes

2020-09-03 03:17 UTC, trbehera approved these changes

2020-09-03 03:19 UTC, merged